engines:
  csslint:
    enabled: true
    checks:
      unique-headings:
        enabled: false
      qualified-headings:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths: []

