version: "22"
checks:
  argument-count:
    config:
      threshold: 6
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
engines:
  csslint:
    enabled: true
    checks:
      unique-headings:
        enabled: false
      qualified-headings:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
    checks:
      no-extend-native:
        enabled: false
      max-statements:
        enabled: false
  fixme:
    enabled: true
  git-legal:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Generic Files LineLength TooLong:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnNewLine:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration SpaceAfterFunction:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakIndent:
        enabled: false
  phpmd:
    enabled: true
    config:
      rulesets: "cleancode,controversial,design,naming,unusedcode,.phpmd.xml"
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      Design/ExitExpression:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
  phan:
    enabled: true
    dead-code-detection: true
    checks:
      PhanUndeclaredClass:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredFunction:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredClassCatch:
        enabled: false
      PhanUndeclaredVariable:
        enabled: false
      PhanUndeclaredConstant:
        enabled: false
  stylelint:
    enabled: true
  sonar-php:
    enabled: true
    checks:
      php:S115:
        enabled: false
      php:S1142:
        enabled: false
      php:S1172:
        enabled: false
      php:S1192:
        enabled: false
      php:S2041:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
  - "node_modules/"
  - "vendor/"
  - "styles/fontello.css"
  - "styles/fontello-ie7.css"

