engines:
  csslint:
    enabled: true
    checks:
      unique-headings:
        enabled: false
      qualified-headings:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnNewLine:
        enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      Design/ExitExpression:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"
  stylelint:
    enabled: true
  sonar-php:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
  - "node_modules/"
  - "vendor/"
  - "styles/fontello.css"
  - "styles/fontello-ie7.css"

